#ifndef FLASH_MEMORY_VALIDATE_TEST_PROJDEF_H
#define FLASH_MEMORY_VALIDATE_TEST_PROJDEF_H

#include "../ExtFlash_ProjDef.h"

/* Individual validation-test controls. */
#define EXT_FLASH_ENABLE_BULK_ACCESS_TEST                 0U
#define EXT_FLASH_ENABLE_QUAD_PARTIAL_FRAME_TEST          0U
#define EXT_FLASH_ENABLE_UNALIGNED_ADDRESS_TEST           0U
#define EXT_FLASH_ENABLE_PAGE_BOUNDARY_WRITE_TEST         0U
#define EXT_FLASH_ENABLE_QUAD_TRANSACTION_BOUNDARY_TEST   0U
#define EXT_FLASH_ENABLE_NORMAL_READ_BOUNDARY_TEST        0U
#define EXT_FLASH_ENABLE_ERASED_DATA_TEST                 0U
#define EXT_FLASH_ENABLE_INVALID_INPUT_TEST               0U

#define EXT_FLASH_ANY_VALIDATION_TEST_ENABLED             \
    (EXT_FLASH_ENABLE_BULK_ACCESS_TEST ||                  \
     EXT_FLASH_ENABLE_QUAD_PARTIAL_FRAME_TEST ||           \
     EXT_FLASH_ENABLE_UNALIGNED_ADDRESS_TEST ||            \
     EXT_FLASH_ENABLE_PAGE_BOUNDARY_WRITE_TEST ||          \
     EXT_FLASH_ENABLE_QUAD_TRANSACTION_BOUNDARY_TEST ||    \
     EXT_FLASH_ENABLE_NORMAL_READ_BOUNDARY_TEST ||         \
     EXT_FLASH_ENABLE_ERASED_DATA_TEST ||                  \
     EXT_FLASH_ENABLE_INVALID_INPUT_TEST)

#define EXT_FLASH_DATA_VALIDATION_TEST_ENABLED            \
    (EXT_FLASH_ENABLE_BULK_ACCESS_TEST ||                  \
     EXT_FLASH_ENABLE_QUAD_PARTIAL_FRAME_TEST ||           \
     EXT_FLASH_ENABLE_UNALIGNED_ADDRESS_TEST ||            \
     EXT_FLASH_ENABLE_PAGE_BOUNDARY_WRITE_TEST ||          \
     EXT_FLASH_ENABLE_QUAD_TRANSACTION_BOUNDARY_TEST ||    \
     EXT_FLASH_ENABLE_NORMAL_READ_BOUNDARY_TEST ||         \
     EXT_FLASH_ENABLE_ERASED_DATA_TEST)

#define EXT_FLASH_NORMAL_READ_VALIDATION_ENABLED          \
    (EXT_FLASH_ENABLE_BULK_ACCESS_TEST ||                  \
     EXT_FLASH_ENABLE_UNALIGNED_ADDRESS_TEST ||            \
     EXT_FLASH_ENABLE_PAGE_BOUNDARY_WRITE_TEST ||          \
     EXT_FLASH_ENABLE_NORMAL_READ_BOUNDARY_TEST)

#define EXT_FLASH_PATTERN_VALIDATION_ENABLED              \
    (EXT_FLASH_ENABLE_BULK_ACCESS_TEST ||                  \
     EXT_FLASH_ENABLE_QUAD_PARTIAL_FRAME_TEST ||           \
     EXT_FLASH_ENABLE_UNALIGNED_ADDRESS_TEST ||            \
     EXT_FLASH_ENABLE_PAGE_BOUNDARY_WRITE_TEST ||          \
     EXT_FLASH_ENABLE_QUAD_TRANSACTION_BOUNDARY_TEST ||    \
     EXT_FLASH_ENABLE_NORMAL_READ_BOUNDARY_TEST)

#define EXT_FLASH_QUAD_PATTERN_VALIDATION_ENABLED         \
    (EXT_FLASH_ENABLE_BULK_ACCESS_TEST ||                  \
     EXT_FLASH_ENABLE_QUAD_PARTIAL_FRAME_TEST ||           \
     EXT_FLASH_ENABLE_UNALIGNED_ADDRESS_TEST ||            \
     EXT_FLASH_ENABLE_PAGE_BOUNDARY_WRITE_TEST ||          \
     EXT_FLASH_ENABLE_QUAD_TRANSACTION_BOUNDARY_TEST)

#define EXT_FLASH_VALIDATION_REPEAT_COUNT              2U
#define EXT_FLASH_BULK_TEST_SIZE_BYTES                 (64U * 1024U)
#define EXT_FLASH_BULK_TEST_CHUNK_SIZE_BYTES           4096U
#define EXT_FLASH_BULK_TEST_SECTOR_SIZE_BYTES          4096U
#define EXT_FLASH_QUAD_BOUNDARY_MAX_LENGTH_BYTES       \
    (QUAD_READ_MAX_TRANSACTION_LENGTH + 1U)
#define EXT_FLASH_VALIDATION_BUFFER_SIZE_BYTES         \
    (EXT_FLASH_QUAD_BOUNDARY_MAX_LENGTH_BYTES + 1U)
#define EXT_FLASH_VALIDATION_CANARY_VALUE              0xA5U
#define EXT_FLASH_VALIDATION_FAILURE_DUMP_LENGTH       16U

#define EXT_FLASH_VALIDATION_AREA_START_ADDRESS        \
    (DATA_PARTITION_END_ADDRESS - EXT_FLASH_BULK_TEST_SIZE_BYTES)
#define EXT_FLASH_BULK_TEST_START_ADDRESS              \
    EXT_FLASH_VALIDATION_AREA_START_ADDRESS

#endif // FLASH_MEMORY_VALIDATE_TEST_PROJDEF_H
