# Match the RSA-2048 key used to sign the application image.
CONFIG_BOOT_SIGNATURE_TYPE_RSA=y
CONFIG_BOOT_SIGNATURE_TYPE_RSA_LEN=2048
CONFIG_BOOT_SIGNATURE_KEY_FILE="C:/SCODE/NXP_Dev/MCXA156/zephyr_440_mcxa156/zephyr/bootloader/mcuboot/root-rsa-2048.pem"
CONFIG_BUILD_OUTPUT_HEX=y
