# Match the public half of the RSA-2048 key used to sign the application image.
CONFIG_BOOT_SIGNATURE_TYPE_RSA=y
CONFIG_BOOT_SIGNATURE_TYPE_RSA_LEN=2048
CONFIG_BOOT_SIGNATURE_KEY_FILE="${APPLICATION_CONFIG_DIR}/keys/wallcontroller_publickey.pem"
CONFIG_BUILD_OUTPUT_HEX=y
