CONFIG_BUILD_OUTPUT_HEX=y
CONFIG_REBOOT=y

CONFIG_THREAD_RUNTIME_STATS=y
CONFIG_THREAD_RUNTIME_STATS_USE_TIMING_FUNCTIONS=y
CONFIG_SCHED_THREAD_USAGE=y
CONFIG_THREAD_MONITOR=y
CONFIG_TIMING_FUNCTIONS=y

CONFIG_PWM=y
CONFIG_SERIAL=y
CONFIG_CAN=y
CONFIG_CAN_FD_MODE=y
CONFIG_CAN_MANUAL_RECOVERY_MODE=y
CONFIG_DAC=y
CONFIG_DMA=y
CONFIG_NXP_INPUTMUX=y
CONFIG_DMA_TCD_QUEUE_SIZE=4

CONFIG_BOOTLOADER_MCUBOOT=y
CONFIG_MCUBOOT_SIGNATURE_KEY_FILE="C:/SCODE/NXP_Dev/MCXA156/zephyr_440_mcxa156/zephyr/bootloader/mcuboot/root-rsa-2048.pem"
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_STREAM_FLASH=y
CONFIG_IMG_MANAGER=y
CONFIG_MCUBOOT_IMG_MANAGER=y
CONFIG_REBOOT=y
