#ifndef NXP_ADC_PROJDEF_H
#define NXP_ADC_PROJDEF_H


#define ADC_IRQ_PRIORITY                        2

#define ADC_STATISTIC_THREAD_PRIORITY           3
#define ADC_MSGQ_LENGTH                         eNUMBER_OF_ADC_CHANNELs
#define ADC_STATISTIC_THREAD_STACK_SIZE         1024
#define ADC_STATS_DEAFULT_MAX_RELEASE_TIME_ms   10U
#define ADC_STATS_DEAFULT_MIN_RELEASE_TIME_ms   10U

#define ADC0_NODE                           DT_NODELABEL(lpadc0)
#define ADC0_DMA_CTLR_NODE                  DT_DMAS_CTLR_BY_NAME(ADC0_NODE, fifoa)
#define ADC0_DMA_CHANNEL                    DT_DMAS_CELL_BY_NAME(ADC0_NODE, fifoa, mux)
#define ADC0_DMA_SLOT                       DT_DMAS_CELL_BY_NAME(ADC0_NODE, fifoa, source)

#define ADC1_NODE                           DT_NODELABEL(lpadc1)
#define ADC1_DMA_CTLR_NODE                  DT_DMAS_CTLR_BY_NAME(ADC1_NODE, fifoa)
#define ADC1_DMA_CHANNEL                    DT_DMAS_CELL_BY_NAME(ADC1_NODE, fifoa, mux)
#define ADC1_DMA_SLOT                       DT_DMAS_CELL_BY_NAME(ADC1_NODE, fifoa, source)

//ADC0 Channel Average Sample Count Limit
#define ADC0_ADC_CH0_AVG_MAX_SAMPLE_COUNT    3
#define ADC0_ADC_CH1_AVG_MAX_SAMPLE_COUNT    3
#define ADC0_ADC_CH2_AVG_MAX_SAMPLE_COUNT    3
#define ADC0_ADC_CH3_AVG_MAX_SAMPLE_COUNT    3
#define ADC0_ADC_CH4_AVG_MAX_SAMPLE_COUNT    3
#define ADC0_ADC_CH5_AVG_MAX_SAMPLE_COUNT    3
#define ADC0_ADC_CH6_AVG_MAX_SAMPLE_COUNT    3
#define ADC0_ADC_CH7_AVG_MAX_SAMPLE_COUNT    3
#define ADC0_ADC_CH8_AVG_MAX_SAMPLE_COUNT    3
#define ADC0_ADC_CH9_AVG_MAX_SAMPLE_COUNT    3
#define ADC0_ADC_CH10_AVG_MAX_SAMPLE_COUNT   3
#define ADC0_ADC_CH11_AVG_MAX_SAMPLE_COUNT   3
#define ADC0_ADC_CH12_AVG_MAX_SAMPLE_COUNT   3
#define ADC0_ADC_CH13_AVG_MAX_SAMPLE_COUNT   3
#define ADC0_ADC_CH14_AVG_MAX_SAMPLE_COUNT   3
#define ADC0_ADC_CH15_AVG_MAX_SAMPLE_COUNT   3
#define ADC0_ADC_CH16_AVG_MAX_SAMPLE_COUNT   3
#define ADC0_ADC_CH17_AVG_MAX_SAMPLE_COUNT   3
#define ADC0_ADC_CH18_AVG_MAX_SAMPLE_COUNT   3
#define ADC0_ADC_CH19_AVG_MAX_SAMPLE_COUNT   3
#define ADC0_ADC_CH20_AVG_MAX_SAMPLE_COUNT   3
#define ADC0_ADC_CH21_AVG_MAX_SAMPLE_COUNT   3
#define ADC0_ADC_CH22_AVG_MAX_SAMPLE_COUNT   3
#define ADC0_ADC_CH23_AVG_MAX_SAMPLE_COUNT   3
#define ADC0_ADC_CH24_AVG_MAX_SAMPLE_COUNT   3
#define ADC0_ADC_CH25_AVG_MAX_SAMPLE_COUNT   3
#define ADC0_ADC_CH26_AVG_MAX_SAMPLE_COUNT   3
#define ADC0_ADC_CH27_AVG_MAX_SAMPLE_COUNT   3
#define ADC0_ADC_CH28_AVG_MAX_SAMPLE_COUNT   3
#define ADC0_ADC_CH29_AVG_MAX_SAMPLE_COUNT   3
#define ADC0_ADC_CH30_AVG_MAX_SAMPLE_COUNT   3
#define ADC0_ADC_CH31_AVG_MAX_SAMPLE_COUNT   3

//ADC1 Channel Average Sample Count Limit
#define ADC1_ADC_CH0_AVG_MAX_SAMPLE_COUNT    3
#define ADC1_ADC_CH1_AVG_MAX_SAMPLE_COUNT    3
#define ADC1_ADC_CH2_AVG_MAX_SAMPLE_COUNT    3
#define ADC1_ADC_CH3_AVG_MAX_SAMPLE_COUNT    3
#define ADC1_ADC_CH4_AVG_MAX_SAMPLE_COUNT    3
#define ADC1_ADC_CH5_AVG_MAX_SAMPLE_COUNT    3
#define ADC1_ADC_CH6_AVG_MAX_SAMPLE_COUNT    3
#define ADC1_ADC_CH7_AVG_MAX_SAMPLE_COUNT    3
#define ADC1_ADC_CH8_AVG_MAX_SAMPLE_COUNT    3
#define ADC1_ADC_CH9_AVG_MAX_SAMPLE_COUNT    3
#define ADC1_ADC_CH10_AVG_MAX_SAMPLE_COUNT   3
#define ADC1_ADC_CH11_AVG_MAX_SAMPLE_COUNT   3
#define ADC1_ADC_CH12_AVG_MAX_SAMPLE_COUNT   3
#define ADC1_ADC_CH13_AVG_MAX_SAMPLE_COUNT   3
#define ADC1_ADC_CH14_AVG_MAX_SAMPLE_COUNT   3
#define ADC1_ADC_CH15_AVG_MAX_SAMPLE_COUNT   3
#define ADC1_ADC_CH16_AVG_MAX_SAMPLE_COUNT   3
#define ADC1_ADC_CH17_AVG_MAX_SAMPLE_COUNT   3
#define ADC1_ADC_CH18_AVG_MAX_SAMPLE_COUNT   3
#define ADC1_ADC_CH19_AVG_MAX_SAMPLE_COUNT   3
#define ADC1_ADC_CH20_AVG_MAX_SAMPLE_COUNT   3
#define ADC1_ADC_CH21_AVG_MAX_SAMPLE_COUNT   3
#define ADC1_ADC_CH22_AVG_MAX_SAMPLE_COUNT   3
#define ADC1_ADC_CH23_AVG_MAX_SAMPLE_COUNT   3
#define ADC1_ADC_CH24_AVG_MAX_SAMPLE_COUNT   3
#define ADC1_ADC_CH25_AVG_MAX_SAMPLE_COUNT   3
#define ADC1_ADC_CH26_AVG_MAX_SAMPLE_COUNT   3
#define ADC1_ADC_CH27_AVG_MAX_SAMPLE_COUNT   3
#define ADC1_ADC_CH28_AVG_MAX_SAMPLE_COUNT   3
#define ADC1_ADC_CH29_AVG_MAX_SAMPLE_COUNT   3
#define ADC1_ADC_CH30_AVG_MAX_SAMPLE_COUNT   3
#define ADC1_ADC_CH31_AVG_MAX_SAMPLE_COUNT   3

#endif
